"""init

Revision ID: 345b8a58281a
Revises: 
Create Date: 2020-11-11 17:33:54.574477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345b8a58281a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=True),
    sa.Column('place_bell', sa.Integer(), nullable=True),
    sa.Column('study_next', sa.Date(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('user')
    # ### end Alembic commands ###
