"""add email to user

Revision ID: 486ceb5d8a2e
Revises: 1690c4f115c2
Create Date: 2020-11-18 16:54:25.775062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486ceb5d8a2e'
down_revision = '1690c4f115c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
