"""mark cards as on_deck

Revision ID: b6e1738eaa17
Revises: d6e877b75109
Create Date: 2020-11-24 13:55:07.013718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e1738eaa17'
down_revision = 'd6e877b75109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('on_deck', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'on_deck')
    # ### end Alembic commands ###
