"""user settings

Revision ID: d6e877b75109
Revises: 486ceb5d8a2e
Create Date: 2020-11-24 12:53:51.540815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e877b75109'
down_revision = '486ceb5d8a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_new', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('max_reviews', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('unlimited_new', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('unlimited_reviews', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unlimited_reviews')
    op.drop_column('user', 'unlimited_new')
    op.drop_column('user', 'max_reviews')
    op.drop_column('user', 'max_new')
    # ### end Alembic commands ###
