"""reinit

Revision ID: fcf602eb4363
Revises: 
Create Date: 2020-11-12 16:19:41.319000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf602eb4363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=True),
    sa.Column('place_bell', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('ease', sa.Float(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('scheduled', sa.Date(), nullable=True),
    sa.Column('learn_mode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_card_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('last_interval', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('card')
    op.drop_table('user')
    # ### end Alembic commands ###
